### ISSUE TITLE
cliptext like EditPlus

### ISSUE THREAD

**Issue by salomalo** [rioj7/regex-text-gen#1]
Hey
I have long been looking for an extension similar to CLIPTEXT from EditPlus
on EDITPLUS is more convenient
src https://www.editplus.com/ss/editplus680x340.png
thanks

**Comment by rioj7** [comment]
@salomalo Is this a request for a new VSC extension? Have you searched the MarketPlace for possible extensions?

**Comment by salomalo** [comment]
no new  VSC , but can someone do
like CLIPTEXT from программ EditPlus

**Comment by rioj7** [comment]
@salomalo How many people do you think read this issue? If you can't find a possible existing extension than you can always ask at StackOverflow.
