### ISSUE TITLE
What is the equivalent of ${TM_SELECTED_TEXT}

### ISSUE THREAD

**Issue by blueray453** [rioj7/regex-text-gen#4]
I have text like bellow:

    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Ut a felis eget enim lobortis fringilla nec fringilla felis.
    Aliquam nec purus quis velit ultricies elementum eget at dui.
    Suspendisse et sapien blandit nulla ornare tincidunt eu a urna.
    Aenean nec nibh varius, interdum odio sed, pharetra metus.

    Cras vitae nisi volutpat, hendrerit massa sed, faucibus risus.
    Nulla sed magna imperdiet, dignissim metus in, dapibus urna.
    Sed dignissim dolor sed faucibus egestas.

I want to wrap with * (using a keyboard shortcut) so that it looks like:

    *Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Ut a felis eget enim lobortis fringilla nec fringilla felis.
    Aliquam nec purus quis velit ultricies elementum eget at dui.
    Suspendisse et sapien blandit nulla ornare tincidunt eu a urna.
    Aenean nec nibh varius, interdum odio sed, pharetra metus.

    Cras vitae nisi volutpat, hendrerit massa sed, faucibus risus.
    Nulla sed magna imperdiet, dignissim metus in, dapibus urna.
    Sed dignissim dolor sed faucibus egestas.*

What i have tried so far is:

    {
        "key": "ctrl+b",
        "command": "regexTextGen.generateText",
        "when": "editorLangId == 'asciidoc' && editorHasSelection",
        "args": {
            "originalTextRegex": "(?gm)(.*)",
            "generatorRegex": "\\*{{0}}\\*"
        }
    },

But it is giving output like:

    *Lorem ipsum dolor sit amet, consectetur adipiscing elit.*

So it is only taking the first line. 

What might be the solution in this case? What is the equivalent of `${TM_SELECTED_TEXT}` here.

**Comment by rioj7** [comment]
@blueray453 If you want this specific application using a snippet is easier to get the result.

```json
{
    "key": "ctrl+b",
    "command": "editor.action.insertSnippet",
    "when": "editorLangId == 'asciidoc' && editorHasSelection && editorTextFocus",
    "args": {
        "snippet": "*${TM_SELECTED_TEXT}*"
    }
}
```

**Comment by blueray453** [comment]
Thank you very much. I actually have what you mentioned as my current keybinding. However, I found that regex-text-gen is pretty powerful. That is why i wanted to know how to use it in this case (as a learning exercise).

**Comment by rioj7** [comment]
@blueray453 I do not support multi line selection (yet) because the logic of the preview code as implemented in VSC and extracted by Yukai Huang was not very readable.

If you need it occasionally you can replace the newlines in the selection with something like `@@`, then apply the regex-text-gen and replace the dummy string with newlines.

Or place multi cursors on each line, apply the regex-text-gen, then select one `*\n*`, then `Ctrl+Shift+L` and then `Enter`.

**Comment by blueray453** [comment]
Thank you very much.
